### ISSUE TITLE
Rexie should implement Send, Sync, Clone, Debug

### ISSUE THREAD

**Issue by xfbs** [devashishdxt/rexie#38]
Hey! I stumbled across Rexie while looking into building a HTTP cache for https://github.com/xfbs/diff.rs. It seems like a really cool project! 

I ran into the issue that while trying to build a custom CacheManager using [http_cache](https://docs.rs/http_cache) using Rexie, it has bounds on the type to implement `Send` and `Sync`. I would also like to add `Clone` and `Debug` implementations, if possible. But it looks like the `Rexie` struct supports none of these.

Is there something that could be done to make this work? Rust complains that Rexie is not `Send` and `Sync` because it uses raw pointers.

**Comment by devashishdxt** [comment]
Hi @xfbs. I think a better option for you is to use [`idb`](https://docs.rs/idb/latest/idb/) crate which provides all the functionality exposed by IndexedDB in browsers (with a slightly lower level API).

`Database` in `idb` already implements `Debug` and for `Clone`, you can just create a new-type and `Database` in `Arc`. For `Send` and `Sync`, I don't think its wise to do for JS based crates because underlying JS objects do not implement `Send` and `Sync`. But, it actually doesn't matter in browsers because the'll anyway run on one thread. You can implement `Send` and `Sync` on you new-type (with some `unsafe` code).

**Comment by xfbs** [comment]
Hey, thanks for the quick reply!I think I was mistaken about needing Send and Sync in the first place, to be honest. It is a constraint of the crate I was trying to integrate with (http_cache) but it seems like I just need to use a conditional on wasm32 compilation and disable those bounds. The other traits I can derive myself or use an Rc as you mentioned. I think you can close this issue then!On 9. Mar 2023, at 02:12, Devashish Dixit ***@***.***> wrote:﻿
Hi @xfbs. I think a better option for you is to use idb crate which provides all the functionality exposed by IndexedDB in browsers (with a slightly lower level API).
Database in idb already implements Debug and for Clone, you can just create a new-type and Database in Arc. For Send and Sync, I don't think its wise to do for JS based crates because underlying JS objects do not implement Send and Sync. But, it actually doesn't matter in browsers because the'll anyway run on one thread. You can implement Send and Sync on you new-type (with some unsafe code).
