### ISSUE TITLE
Transaction abort hangs indefinitely

### ISSUE THREAD

**Issue by tobiemh** [devashishdxt/rexie#6]
Hi! First of all, thanks for this library, the API makes working with IndexedDB so much better! I think I've found a bug when calling `abort()` on a transaction.

When running the following code, the returned JavaScript promise never resolves, and the `abort()` method hangs indefinitely. The 'Transaction aborted' message never gets logged. In addition, the value is actually committed and stored in IndexedDB.

```rust
#[wasm_bindgen]
pub async fn temp() -> Result<JsValue, JsValue> {
    let db = Rexie::builder("temp").version(1).add_object_store(ObjectStore::new("kv")).build().await?;
    let tx = db.transaction(&["kv"], TransactionMode::ReadWrite)?;
    let st = tx.store("kv")?;
    st.put(&JsValue::from("test"), Some(&JsValue::from("test"))).await?; // Removing this makes no difference
    trace!("Transaction aborting");
    let xx = tx.abort().await?;
    trace!("Transaction aborted");
    Ok(JsValue::TRUE)
}
```

For comparison, the following code works correctly, and the value is committed and stored in IndexedDB. The 'Transaction committed' message is logged successfully.

```rust
#[wasm_bindgen]
pub async fn temp() -> Result<JsValue, JsValue> {
    let db = Rexie::builder("temp").version(1).add_object_store(ObjectStore::new("kv")).build().await?;
    let tx = db.transaction(&["kv"], TransactionMode::ReadWrite)?;
    let st = tx.store("kv")?;
    st.put(&JsValue::from("test"), Some(&JsValue::from("test"))).await?;
    trace!("Transaction committing");
    let rx = tx.commit().await?;
    trace!("Transaction committed");
    Ok(JsValue::TRUE)
}
```

I'm testing this with `rexie-0.2.1`

**Comment by devashishdxt** [comment]
Hi @tobiemh,

Thanks for creating this issue!

This was a silly bug where it was waiting for a transaction to be aborted without calling `abort`. 🤦🏻‍♂️

Anyway, this issue forced me to delve deeper into IndexedDB's transaction processing and I found that the `commit` feature is still in working draft. Current `commit` function in this crate is not forcing the DB to commit the values but waiting for DB to perform auto-commit. I've changed `commit` -> `done` (and updated documentation) so that we can add a `commit` function to transaction when that feature becomes available in IndexedDB.

I'll release a new version soon (Unfortunately it'll be a breaking change).
